language: r
cache: packages

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

r_binary_packages:
  - magrittr
  - lazyeval
  - mime
  - curl
  - openssl
  - R6
  - jsonlite
  - httr
  - crayon
  - reshape2
  - ncdf4
  - data.table
  - coda
  - testthat
  - digest
  - praise
  - R.rsp
  - knitr
  - covr

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      FORMULA="libbi";
      brew cask uninstall --force oclint;
      brew tap sbfnk/libbi;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      LINUXBREW="/home/linuxbrew/.linuxbrew";
      export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH";
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
      FORMULA="libbi-linux";
      brew install libgcrypt;
      brew tap sbfnk/libbi;
      chmod 644 $LINUXBREW/Homebrew/Library/Taps/sbfnk/homebrew-libbi/"$FORMULA".rb;
    fi
  - brew install sbfnk/libbi/$FORMULA; true
  - which R
  - env
  - R -e 'Sys.getenv()'
