language: r
cache: packages
warnings_are_errors: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

r_binary_packages:
  - magrittr
  - lazyeval
  - mime
  - curl
  - openssl
  - R6
  - jsonlite
  - httr
  - crayon
  - reshape2
  - ncdf4
  - data.table
  - coda
  - testthat
  - digest
  - praise

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo chown -R $USER $(brew --repo);
      sudo chown -R $USER $(brew --prefix);
      brew tap homebrew/science;
      brew install gcc;
      brew link --overwrite gcc;
      brew install libbi;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo mkdir -p /home/linuxbrew;
      sudo chown "$USER" /home/linuxbrew;
      LINUXBREW=/home/linuxbrew/.linuxbrew;
      git clone https://github.com/Linuxbrew/brew.git "$LINUXBREW";
      export PATH="$LINUXBREW/bin:$PATH";
      export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed 's/:$//');
      brew tap homebrew/science;
      brew install sbfnk/libbi/libbi;
      mkdir -p ~/.R;
      printf "CC=/usr/bin/gcc\nCXX/usr/bin/g++"  > ~/.R/Makevars;
    fi

